name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        key: ${{ secrets.TEST_VM_SSH }}
        host: ${{ secrets.TEST_VM_IP }}
        username: ${{ secrets.TEST_VM_USERNAME }}
        script: |
          pm2 delete all
          cd D:/nodejsdeploy
          git pull
          npm install
          pm2 start npm -- start

        
        
